package ru.infos.dcn.server.dao.entity;
// Generated 08.11.2009 17:20:23 by Hibernate Tools 3.2.0.b11


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Long commentId;
     private String comment;
     private Date timestamp;
     private Long authorId;

    public Comment() {
    }

	
    public Comment(String comment, Long authorId) {
        this.comment = comment;
        this.authorId = authorId;
    }
    public Comment(String comment, Date timestamp, Long authorId) {
       this.comment = comment;
       this.timestamp = timestamp;
       this.authorId = authorId;
    }
   
    public Long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Long getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }




}


