package ru.infos.dcn.server.dao.entity;
// Generated 08.11.2009 17:20:23 by Hibernate Tools 3.2.0.b11


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import ru.infos.dcn.server.dao.entity.Comment;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Long postId;
     private Integer version;
     private String subject;
     private String text;
     private Date timestamp;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Post() {
    }

    public Post(String subject, String text, Date timestamp, Set<Comment> comments) {
       this.subject = subject;
       this.text = text;
       this.timestamp = timestamp;
       this.comments = comments;
    }
   
    public Long getPostId() {
        return this.postId;
    }
    
    public void setPostId(Long postId) {
        this.postId = postId;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


